<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	  $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
            <?php /* @escapeNotVerified */ echo __('Availability:') ?><span><?php echo $stockItem = $StockState->getStockQty($_product->getId(), $_product->getStore()->getWebsiteId()); echo "&nbsp"; ?><?php /* @escapeNotVerified */ echo __('In stock') ?>
    </span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
            <?php /* @escapeNotVerified */ echo __('Availability:') ?><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
