<?php
$listRelays = $block->getListRelays();
$openingDays = array('horairesOuvertureLundi', 'horairesOuvertureMardi', 'horairesOuvertureMercredi', 'horairesOuvertureJeudi', 'horairesOuvertureVendredi', 'horairesOuvertureSamedi', 'horairesOuvertureDimanche');

foreach ($listRelays as $i => $oneRelay) { ?>
    <div class="lpc_layer_relay" id="lpc_layer_relay_<?php echo $i; ?>" data-relayindex="<?php echo $i; ?>">
        <div class="lpc_layer_relay_name"><?php echo $oneRelay->nom ?></div>
        <div class="lpc_layer_relay_address">
			<span class="lpc_layer_relay_country_code"><?php echo $oneRelay->codePays; ?></span>
			<span class="lpc_layer_relay_type"><?php echo $oneRelay->typeDePoint; ?></span>
            <span class="lpc_layer_relay_id"><?php echo $oneRelay->identifiant; ?></span>
            <span class="lpc_layer_relay_address_street"><?php echo $oneRelay->adresse1; ?></span>
            <span class="lpc_layer_relay_address_zipcode"><?php echo $oneRelay->codePostal; ?></span><?php echo " "; ?>
            <span class="lpc_layer_relay_address_city"><?php echo $oneRelay->localite ?></span>
            <span class="lpc_layer_relay_latitude"><?php echo $oneRelay->coordGeolocalisationLatitude; ?></span>
            <span class="lpc_layer_relay_longitude"><?php echo $oneRelay->coordGeolocalisationLongitude; ?></span>
            <div>
                <span class="lpc_show_relay_details"><?php echo __("Display") ?></span>
            </div>
            <div class="lpc_layer_relay_schedule">
                <table cellpadding="0" cellspacing="0">
                    <?php
                    foreach ($openingDays as $oneDay) {
                        if ($oneRelay->$oneDay != '00:00-00:00 00:00-00:00') { ?>
                            <tr>
                                <td class="opening_hours"><?php echo $block->formatRelaysOpeningHours($oneRelay->$oneDay); ?></td>
                            </tr>
                        <?php }
                    }
                    ?>
                </table>
            </div>
            <div class="lpc_layer_relay_distance"><?php echo __('At')." ";
                echo $oneRelay->distanceEnMetre ?> m
            </div>
        </div>
        <div class="lpc_relay_choose_btn">
            <button class="lpc_relay_choose" type="button" data-relayindex="<?php echo $i; ?>"><?php echo __('Choose') ?></button>
        </div>

    </div>
    <?php if (($i + 1) < count($listRelays)) { ?>
        <hr style="width: 100%">
    <?php } ?>

<?php } ?>