<?php

/*******************************************************
 * Copyright (C) 2019 La Poste.
 *
 * This file is part of La Poste - Colissimo module.
 *
 * La Poste - Colissimo module can not be copied and/or distributed without the express
 * permission of La Poste.
 *******************************************************/

/* @var $block \LaPoste\Colissimo\Block\System\Config\Field\FmtFileExample */?>


<?php echo $block->getButtonHtml(); ?>
