<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter">
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail-footer">
			<img title="<?php echo $this->helper('\Magento\Cms\Helper\Wysiwyg\Images')->getBaseUrl();?>" src="<?php echo $this->helper('\Magento\Cms\Helper\Wysiwyg\Images')->getBaseUrl();?>icon-paperplane.png">
            <p>Inscrivez-vous à notre newsletter :</p>
            <div class="field form-group newsletter">
                <div class="control">
                    <input name="email" type="email" id="newsletter-footer"
                                placeholder="<?php /* @escapeNotVerified */ echo __('email address') ?>"
								autocorrect="off" 
								title="Abonnez-vous à la newsletter"
                                data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe btn btn-primary btn-sm" title="<?php /* @escapeNotVerified */ echo __('Valider') ?>" type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Valider') ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
