<div class="lpc_balreturn">
    <h1 class="page-title"><?php echo __('MailBox picking return'); ?></h1>

    <h2 class="lpc_balreturn_subtitle"><?php echo __('Retrieval address'); ?></h2>
    <div>
        <?php echo __('Address from which the return will be from:'); ?>
        <form method="POST" action="<?php echo $this->getUrl('*/*/confirm'); ?>">
            <div class="lpc_balreturn_withseparator">
                <?php echo $this->formatFormAddress(); ?>
            </div>
            <?php if ($this->getListMailBoxPickingDatesResponse()) {
                $address = $this->getRequest()->getParam('address'); ?>
                <input type="hidden" id="lpc_bal_companyName" name="address[companyName]" value="<?php echo $address['companyName']; ?>"/>
                <input type="hidden" id="lpc_bal_street" name="address[street]" value="<?php echo $address['street']; ?>"/>
                <input type="hidden" id="lpc_bal_zipCode" name="address[zipCode]" value="<?php echo $address['zipCode']; ?>"/>
                <input type="hidden" id="lpc_bal_city" name="address[city]" value="<?php echo $address['city']; ?>"/>
                <input type="hidden" id="lpc_bal_pickingDate" name="pickingDate" value="<?php echo $this->getListMailBoxPickingDatesResponse()->mailBoxPickingDates[0]; ?>"/>
                <input type="hidden" id="lpc_bal_shipmentId" name="shipmentId" value="<?php echo $this->getShipment()->getId(); ?>"/>
                <p><?php echo sprintf(
                        __('Please confirm before today %s that you will put the parcel in the MailBox described previously, before the %s at %s.'),
                        $this->getListMailBoxPickingDatesResponse()->validityTime,
                        $this->getMailBoxPickingDate(),
                        $this->getListMailBoxPickingDatesResponse()->mailBoxPickingDateMaxHour
                    ); ?></p>
                <div>
                    <button class="lpc_balreturn_btn" type="submit"><?php echo __('Confirm Pick-Up'); ?></button>
                </div>
                <?php
            } else {
                ?>
                <p><b><?php echo __('This address is not eligible for MailBox pick-up.'); ?></b></p>
                <?php
            } ?>

        </form>
    </div>
</div>
