<div class="lpc_balreturn">
    <h1 class="page-title"><?php echo __('MailBox picking return'); ?></h1>

    <?php $initialShippingAddress = $this->getShipment()->getShippingAddress(); ?>


    <h2 class="lpc_balreturn_subtitle"><?php echo __('Retrieval address'); ?></h2>
    <div class="lpc_balreturn_shipping lpc_balreturn_withseparator">
        <div>
            <?php echo __('Your shipment was initially sent to the following address:'); ?>
        </div>
        <div class="lpc_balreturn_shipping_address">
            <?php echo $this->addressFormatter($initialShippingAddress); ?>
        </div>
    </div>

    <div class="lpc_balreturn_address">
        <div><?php echo __('You may change the address the return will be made from via the following fields:'); ?></div>
        <form method="POST" action="<?php echo $this->getUrl('*/*/checkAvailibility'); ?>">
            <input type="hidden" id="lpc_bal_shipmentId" name="shipmentId" value="<?php echo $this->getShipment()->getId(); ?>"/>
            <div>
                <label for="lpc_bal_companyName"><?php echo __('Name') ?></label>
                <input type="text" id="lpc_bal_companyName" name="address[companyName]" value="<?php echo $initialShippingAddress->getName() ?>"/>
            </div>
            <div>
                <label for="lpc_bal_street"><?php echo __('Street') ?></label>
                <input type="text" id="lpc_bal_street" name="address[street]" value="<?php echo implode(', ', $initialShippingAddress->getStreet()); ?>"/>
            </div>
            <div>
                <label for="lpc_bal_zipCode"><?php echo __('Zip code') ?></label>
                <input type="text" id="lpc_bal_zipCode" name="address[zipCode]" value="<?php echo $initialShippingAddress->getPostCode() ?>"/>
            </div>
            <div>
                <label for="lpc_bal_city"><?php echo __('City') ?></label>
                <input type="text" id="lpc_bal_city" name="address[city]" value="<?php echo $initialShippingAddress->getCity() ?>"/>
            </div>
            <div>
                <label for="lpc_bal_country"><?php echo __('Country') ?></label>
                <input type="text" id="lpc_bal_country" name="address[country]" value="FR" readonly="true" disabled="true"/>
                <i><?php echo __('Only France is allowed'); ?></i>
            </div>


            <div class="lpc_balreturn_btn">
                <button type="submit"><?php echo __('Check that this address is allowed for MailBox picking return'); ?></button>
            </div>
        </form>
    </div>
</div>
