<?php $_aHelper = $this->helper('MGS\AjaxCart\Helper\Data'); ?>
<?php $animationType = $_aHelper->getConfig('ajaxcart/additional/animation_type'); ?>
<?php if ($animationType == 'cartshow') : ?>
    <script type="text/javascript">
        requirejs(['jquery', 'mgs_quickview'],
            function($, quickview) {
                $(document).ready(function() {
                    $('.mgs-quickview').bind('click', function() {
                        var prodUrl = $(this).attr('data-quickview-url');
                        if (prodUrl.length) {
                            quickview.displayContent(prodUrl, true);
                        }
                    });
                });
            });
    </script>
<?php else : ?>
    <script type="text/javascript">
        requirejs(['jquery', 'mgs_quickview'],
            function($, quickview) {
                $(document).ready(function() {
                    $('.mgs-quickview').bind('click', function() {
                        var prodUrl = $(this).attr('data-quickview-url');
                        if (prodUrl.length) {
                            quickview.displayContent(prodUrl, false);
                        }
                    });
                });
            });
    </script>
<?php endif; ?>