<?php $lpcRelayInformation = $block->lpcGetRelayInformation();
if (!empty($lpcRelayInformation['relayId'])) { ?>
	<div class="admin__page-section-item-title">
		<span class="title"><?php echo __('Colissimo relay') ?></span>
	</div>

	<div class="admin__page-section-item-content">

        <?php if (!empty($lpcRelayInformation['relayName'])) {
            echo $lpcRelayInformation['relayName'];
            echo "<br>";
        } ?>

        <?php echo __('id').': '.$lpcRelayInformation['relayId'] ?>
	</div>

<?php } ?>
