<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \LaPoste\Colissimo\Helper\Data $helperData
 */

$helperData = $this->helper('\LaPoste\Colissimo\Helper\Data')
?>

<?php if (!$helperData->isUsingColiShip()): ?>
    <?= __('ColiShip export functionalities are only available when ColiShip is used in the configuration.');?>
<?php else: ?>
    <?= $block->getChildHtml(); ?>
<?php endif; ?>
